### ISSUE TITLE
some changes in example_SoilTemp

### ISSUE THREAD

**Issue by cyrillemidingoyi** [AgriculturalModelExchangeInitiative/xml_representation#2]
ModelUnit.dtd in "http://simplace.net/dtd/ModelUnit.dtd" is different from this one on github
So example_SoilTemp.xml is not validated with the DTD on github
In order to be conformed to ModelUnit.dtd in this github:
1 - There is no attribute named "frequency" in ModelUnit element:
	- Attribute "uniqueid", "name" are required and must be specified for element type  "ModelUnit".
2- The content of element type "Description" must match "(Title,Authors,Institution,URI?,Reference?,Abstract)". Not "Author" but "Authors"

**Comment by cyrillemidingoyi** [comment]
We can also replace "frequency" by "timestep" to be conformed with the DTD

**Comment by pradal** [comment]
Fixed
